### PR TITLE
PR: Prevent raising an exception when a file in a monitored folder has no permissions

### PR DESCRIPTION
**Pull request by andfoy**
Fixes https://github.com/spyder-ide/spyder/issues/12636

cc @ccordoba12

### CODE REVIEW

**Comment by ccordoba12** [comment]
Some context about this PR: Spyder uses Watchdog to keep track of file changes in our projects. However, if a user creates a project in a directory with no access permissions, then this error is raised.

**Comment by BoboTiG** [comment]
Hey @andfoy and @ccordoba12,

Thanks for the patch, very appreciated :)

I will have a look tomorrow or monday and we will then manage to release a new version including the fix.

**Comment by ccordoba12** [comment]
Thanks a lot for your help @BoboTiG!

**Comment by BoboTiG** [comment]
The version 0.10.3 online :)

**Comment by ccordoba12** [comment]
Thanks @BoboTiG!

**Pull request merged**
