### PR TITLE
Return byte paths if a byte path was given on macOS

### PR DESCRIPTION
**Pull request by SamSchott**
This fixes an issue on macOS where file system events would always be generated with unicode paths, even if a byte path was passed to the observer.

### CODE REVIEW

**Comment by CCP-Aporia** [comment]
Would you be open to do this type conversion in the C extension directly? It is possible to keep track there if it was a string (= unicode) or bytes object that was passed in. And it would mean that everyone who uses `NativeEvent` directly gets the same behaviour.

**Comment by SamSchott** [comment]
Sure. I have pretty much zero experience with C or Python's C API. So maybe you are better suited to make those changes?

**Comment by CCP-Aporia** [comment]
Absolutely no problem, I'll take a stab at this over the weekend. Until then I think it's fine to have this solution as well.

**Comment by BoboTiG** [comment]
Thanks :)

**Pull request merged**
