### PR TITLE
Fix watch descriptors not updating when moving nested subdirectories

### PR DESCRIPTION
**Pull request by BoboTiG**
Original patch by Zack Morris (@zackmorris) on issue #325.

### CODE REVIEW

**Comment by BoboTiG** [comment]
@rrzaripov do you mind reviewing this one too? It may help with #514 too.

**Comment by rrzaripov** [comment]
@BoboTiG this patch very similar to #515, so I think this one we can to close.

**Comment by BoboTiG** [comment]
Yep, do you think you can copy the test case into your branch?

**Comment by rrzaripov** [comment]
@BoboTiG yes, I think this is good idea, test appended to #515

**Pull request closed without merging**
