### PR TITLE
Add `DirectorySnapshotDiff.ContextManager`

### PR DESCRIPTION
**Pull request by msabramo**
A context manager that creates two directory snapshots and a diff object that represents the difference between the two snapshots.

```python
dir_snapshot_diff_context_manager = DirectorySnapshotDiff.ContextManager("some_path")
with dir_snapshot_diff_context_manager:
    # Do some things that change files...
    ...

print(dir_snapshot_diff_context_manager.diff.files_created)
print(dir_snapshot_diff_context_manager.diff.files_deleted)
```

### CODE REVIEW

**Comment by BoboTiG** [comment]
That is awesome :)
Would you mind rebasing your branch on master to benefit of your older PR (+ resolving conflicts ofc) 🙏🏻 ?

**Comment by msabramo** [comment]
> Would you mind rebasing your branch on master to benefit of your older PR (+ resolving conflicts ofc) 🙏🏻 ?

Would be happy to! Done!

**Comment by BoboTiG** [comment]
I just saw mypy issues. Are they related to the previous PR? 🤔

**Comment by msabramo** [comment]
> I just saw mypy issues. Are they related to the previous PR? 🤔

See #1014...

**Comment by BoboTiG** [comment]
Thank you @msabramo 🍾

**Pull request merged**
