### PR TITLE
Fix Python 3.6 installation when the OS locale is set to POSIX

### LINKED ISSUE #615: Watchdog v0.10.0 fails to install (UnicodeDecodeError): v0.9.0 works fine
```
Collecting watchdog>=0.6.0
  Downloading watchdog-0.10.0.tar.gz (94 kB)
[91m    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xt0go193/watchdog/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xt0go193/watchdog/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-xt0go193/watchdog/pip-egg-info
         cwd: /tmp/pip-install-xt0go193/watchdog/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xt0go193/watchdog/setup.py", line 86, in <module>
        changelog = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 63: ordinal not in range(128)
    ----------------------------------------
[0m[91mERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### PR DESCRIPTION
**Pull request by tehkirill**
Fixes #615.

### CODE REVIEW

**Comment by BoboTiG** [comment]
To fix errors, maybe this line at the top of the file would be better:
```python
from codecs import open
```
Also, can you add your GH nickname + history change? I am thinking of something like:
> Fixed Python 3.6 installation when the OS locale is set to POSIX

**Comment by tehkirill** [comment]
> To fix errors, maybe this line at the top of the file would be enough:
> 
> ```python
> from codecs import open
> ```
Good shout, was going to go via `.decode()` route originally.

**Comment by BoboTiG** [comment]
Thanks a lot @tehkirill :)

**Comment by tdhopper** [comment]
@BoboTiG are you able to cut a release to pypi?

**Comment by darakian** [comment]
A new pypi release would be very helpful.

**Comment by BoboTiG** [comment]
@darakian Done :)

**Comment by darakian** [comment]
Thank you much @BoboTiG :)

**Pull request merged**
