### PR TITLE
Add logger parameter for the LoggingEventHandler.

### PR DESCRIPTION
**Pull request by Sraw**
As the title says, this PR adds a new parameter to the LoggingEventHandler so that it won't use root logger anymore if a logger is passed in.

### CODE REVIEW

**Comment by BoboTiG** [comment]
Thanks for the PR @Sraw.

Again, if you could add a line in the changelog, it would be great :)

**Comment by Sraw** [comment]
Hi, I've updated the changelog for both PRs.

**Comment by BoboTiG** [comment]
Well, then there is a conflict to fix :)

**Comment by Sraw** [comment]
Done!

**Comment by BoboTiG** [comment]
Thanks :)

**Pull request merged**
