### PR TITLE
Include conftest.py into sdist

### PR DESCRIPTION
**Pull request by kapsh**
Fixtures were missing when running tests on sources from pypi tarball.

### CODE REVIEW

**Comment by BoboTiG** [comment]
I would prefer moving the file `conftest.py` into the `tests` folder, which is where it should be from the beginning.

**Comment by kapsh** [comment]
Fine by me, I can do it and check if it works later today.

**Comment by kapsh** [comment]
That will do.

**Comment by BoboTiG** [comment]
Thanks @kapsh!

**Pull request merged**
