### PR TITLE
drop pull_request: paths: constraints

### PR DESCRIPTION
**Pull request by altendky**
This is open to much opinion.  I find it a hassle to maintain and also risky.  For example, `tests.yml` uses tox and thus `tox.ini` but as is editing that file wouldn't trigger a run.  Let me know how you feel about this.

### CODE REVIEW

**Comment by BoboTiG** [comment]
We could simplify further by removing `branches`, right?

**Comment by altendky** [comment]
Then you wouldn't get builds when the PR is merged to `master`.  You generally want this both to have a record of builds associated to the commits on the branch and also because the last build on a PR may be out of date, `master` may have moved forward since it, so you at least get a post-merge check just in case.  There are lots of topics around the second bit if we want to discuss a layer or two deeper.

**Comment by BoboTiG** [comment]
Hm I thought those two were the same:
```yml
pull_request:
```
```yml
pull_request:
    branches:
      - "**"
```
🤔

**Comment by altendky** [comment]
Oh sorry, I went and thought about the other `branches:` entry.  I think you can leave it totally empty as you said.  I feel like there may have been some nuances around that, but I don't recall for sure.  I can remove it if you prefer.  Explicit has some value.

**Pull request merged**
