### PR TITLE
Addresses the issue of out of order events

### PR DESCRIPTION
**Pull request by Arash-Afshar**
Essentially I am sorting the events based on their mtime. Events with the same mtime are added sequentially.

### CODE REVIEW

**Comment by SamSchott** [comment]
Are there any plan to address this? It would fix for instance #538.

**Comment by gpalomar** [comment]
Hi! I need this fix. Default .txt editor for MAC users is TextEdit. Will this fix #538 ? Thanks!

**Comment by BoboTiG** [comment]
Should have been fixed with #734 and #750, right @SamSchott?

**Comment by SamSchott** [comment]
Yes!

**Comment by BoboTiG** [comment]
Thanks for the effort @Arash-Afshar :)

**Pull request closed without merging**
