### PR TITLE
Removed argh from watchmedo and replaced with argparse

### PR DESCRIPTION
**Pull request by AndreaRe9**
Hello everyone!

Starting from what was suggested by @BoboTiG in a comment regarding issue #824 , I modified the code of `watchmedo.py` in order to replace argh with argparse.
To implement the argument parser with `argparse`, I used a code snippet that I found [here](https://gist.github.com/mivade/384c2c41c3a29c637cb6c603d4197f9f), which was quite useful to get things done more elegantly.
I did some very basic tests using the `log` command, but in-depth tests are certainly required for all the commands, maybe from more experienced users of this tool.

**Note:** Please note that this PR is not ready to be merged yet. Feedback is needed.

### CODE REVIEW

**Comment by BoboTiG** [comment]
It seems promising :+1: 

Could you also remove `argh` from https://github.com/gorakhargosh/watchdog/blob/5a7022cf8d1a5b0ba1e52882e9424cdf7167e829/setup.py#L81 and everywhere in documentations also?

**Comment by AndreaRe9** [comment]
Done!
Do you think that I can mark this PR ready for review?

**Comment by BoboTiG** [comment]
If we merge that Pr, do we loose commands or arguments? I am thinking about aliases that are commented.

**Comment by AndreaRe9** [comment]
You were right @BoboTiG about aliases, I was missing them. I think that all the commands should be okay now.

**Comment by BoboTiG** [comment]
> Do you think that I can mark this PR ready for review?

Yes :)

**Comment by BoboTiG** [comment]
Thanks a lot @AndreaRe9 :champagne:

**Comment by ktdreyer** [comment]
Thanks! Would you mind shipping a new release to PyPI with this change?

**Comment by BoboTiG** [comment]
@ktdreyer will do tonight or tomorrow :+1: (French timezone).

**Comment by BoboTiG** [comment]
[v2.1.6](https://github.com/gorakhargosh/watchdog/releases/tag/v2.1.6) released :champagne:

**Pull request merged**
