### PR TITLE
Use scandir to save memory

### PR DESCRIPTION
**Pull request by QuantumEnergyE**
Use `scandir` to save memory.

### CODE REVIEW

**Comment by BoboTiG** [comment]
Thanks, LGTM.

Could you remove the `import os` from `polling.py`? It becomes useless.

**Comment by QuantumEnergyE** [comment]
> useless

I have removed `import os`  from `polling.py`

**Comment by QuantumEnergyE** [comment]
> Thanks, LGTM.
> 
> Could you remove the `import os` from `polling.py`? It becomes useless.

I have removed `import os`  from `polling.py`

**Comment by BoboTiG** [comment]
Last thing, perhaps [this line](https://github.com/gorakhargosh/watchdog/pull/503/files#diff-37544e4f4fc710fd03bf1370a3d6f1a8R200) should mention `os.scandir`. Something like:

 > Use custom listdir function. For details see ``os.scandir`` if available, else ``os.listdir``.

**Comment by QuantumEnergyE** [comment]
> Last thing, perhaps [this line](https://github.com/gorakhargosh/watchdog/pull/503/files#diff-37544e4f4fc710fd03bf1370a3d6f1a8R200) should mention `os.scandir`. Something like:
> 
> > Use custom listdir function. For details see `os.scandir` if available, else `os.listdir`.

Thanks,PTAL.

**Comment by BoboTiG** [comment]
Thanks @QuantumEnergyE!

**Pull request merged**
